name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8
    - name: Set up cloudformation-cli-java-plugin
      run: |
        pip install cloudformation-cli-java-plugin
        pip uninstall -y jinja2
        pip install Jinja2==2.10.1
    - name: install and run pre-commit
      uses: pre-commit/action@v2.0.0
      with:
        extra_args: --all-files
    - name: Install aws-wafv2-commons
      run: |
        cd "${GITHUB_WORKSPACE}/aws-wafv2-commons"
        mvn clean install
    - name: Run maven verify for all resources
      run: |
        for directory in $GITHUB_WORKSPACE/aws-*; do
          test "$directory" = "$GITHUB_WORKSPACE/aws-wafv2-commons" && continue
          cd "$directory"
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
          cat rpdk.log
        done
    - name: Output rpdk.log
      if: ${{ failure() }}
      run: |
        for directory in $GITHUB_WORKSPACE/aws-*; do
          test "$directory" = "$GITHUB_WORKSPACE/aws-wafv2-commons" && continue
          echo "cat rpdk.log for $directory"
          cd "$directory"
          if [ "$(ls -A rpdk.log)" ]; then
            cat rpdk.log          
          fi
        done

